server:
  port: 8081

spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

  h2:
    console:
      enabled: false

  mail:
    host: localhost
    port: 2525
    username: test@test.com
    password: password
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

  rabbitmq:
    addresses: localhost:5672
    username: guest
    password: guest

rabbit:
  mailQueueName: mail_details_queue_test

